apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: microsoft 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microsoft 
    spec:
      containers:
        - name: microsoft 
          image: samaraprueba.azurecr.io/microsoft
          ports:
          - containerPort: 8080